# config.yaml local
http_port: ":8080"
db_url: "postgres://postgres:postgres@postgres:5432/furniture?sslmode=disable"
redis_addr: "redis:6379"
kafka_brokers: ["kafka:9092"]
jwt_secret: "talesofrussianglubinka"
read_timeout: 15s
write_timeout: 15s
idle_timeout: 60s
cors_debug: false
# S3 app config 
max_upload_size: 10485760 # 10MB в байтах
allowed_image_types: ["image/jpeg", "image/png", "image/webp"]

aws:
  region: "us-east-1"
  access_key_id: "furniture"
  secret_access_key: "furniture"
  s3_bucket: "furniture"
  s3_host: "furniture-s3"
